// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateCode(arg1:string):Promise<string>;

export function GenerateDatabaseCode(arg1:string):Promise<string>;

export function GolangVersion():Promise<string>;

export function SettingGet():Promise<string>;

export function SettingSet(arg1:string):Promise<void>;

export function Version():Promise<string>;

export function WorkSpaceConfigGet():Promise<string>;

export function WorkSpaceConfigSave(arg1:string):Promise<void>;

export function WorkSpaceGet():Promise<string>;

export function WorkSpaceInit(arg1:string):Promise<void>;

export function WorkSpaceSet(arg1:string):Promise<string>;
