// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SettingGet() {
  return window['go']['main']['App']['SettingGet']();
}

export function SettingSet(arg1) {
  return window['go']['main']['App']['SettingSet'](arg1);
}
