// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GolangVersion() {
  return window['go']['main']['App']['GolangVersion']();
}

export function SettingGet() {
  return window['go']['main']['App']['SettingGet']();
}

export function SettingSet(arg1) {
  return window['go']['main']['App']['SettingSet'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WorkSpaceConfigGet() {
  return window['go']['main']['App']['WorkSpaceConfigGet']();
}

export function WorkSpaceConfigSave(arg1) {
  return window['go']['main']['App']['WorkSpaceConfigSave'](arg1);
}

export function WorkSpaceGet() {
  return window['go']['main']['App']['WorkSpaceGet']();
}

export function WorkSpaceInit(arg1) {
  return window['go']['main']['App']['WorkSpaceInit'](arg1);
}

export function WorkSpaceSet(arg1) {
  return window['go']['main']['App']['WorkSpaceSet'](arg1);
}
