// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SettingGet():Promise<string>;

export function SettingSet(arg1:string):Promise<void>;
